#include "locusta.h"
#include <errno.h>
#include <fenv.h>
#include <limits.h>
#include <math.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>

static inline double get_time(void) {
  struct timeval tv;
  gettimeofday(&tv, NULL);
  return tv.tv_sec + (double)tv.tv_usec / 1000000;
}

static inline void help(char *name) {
  printf("Usage ./%s -t  target_pid -i signal1[,signal2,...] [-p period] [-d "
         "initial delay]\n",
         name);
}

int main(int argc, char **argv) {
  int num_signals_to_send = 0, *signals_to_send = NULL, period_id = 0;
  pid_t target = 0;
  int res, opt, recv_sig = 0;
  double time_spec;
  long seconds, nanoseconds;
  timer_t period_timer;
  struct sigaction sa;
  struct sigevent event;
  struct itimerspec timer_spec;
  struct timespec initial_delay = {0, 1}, period = {0};
  sigset_t mask;
  res = sigemptyset(&mask);
  if (res < 0) {
    fprintf(stderr, "Cannot empty signal mask\n");
    return -1;
  }
  do {
    opt = getopt(argc, argv, "-ht:s:d:p:");
    switch (opt) {
    case 's':
      char *tmp_signal = NULL;
      int signal_to_send = 0;
      tmp_signal = strtok(optarg, ";,");
      while (tmp_signal != NULL) {
        signal_to_send = strtol(tmp_signal, NULL, 10);
        if (signal_to_send < 0 || signal_to_send > DUMMY_SIGNALS +
                                                       (SW_DSTS * SW_MODES) +
                                                       (HW_DSTS + HW_MODES)) {
          fprintf(stderr, "Signal out of range\n");
          help(argv[0]);
          return -1;
        }
        num_signals_to_send++;
        if (signals_to_send == NULL) {
          signals_to_send = malloc(sizeof(int));
          if (signals_to_send == NULL) {
            fprintf(stderr, "Cannot allocate memory for signal list\n");
            return -1;
          }

        } else {
          int *new_signals_to_send =
              reallocarray(signals_to_send, num_signals_to_send, sizeof(int));
          if (new_signals_to_send == NULL) {
            fprintf(stderr, "Cannot reallocate memory for signal list\n");
            free(signals_to_send);
            return -1;
          }
          signals_to_send = new_signals_to_send;
        }
        signals_to_send[num_signals_to_send - 1] =
            MIGRATION_SIGNAL + signal_to_send;
        tmp_signal = strtok(NULL, ",");
      }
      break;
    case 'p':
    case 'd':
      // common operations to convert the delay or period from a decimal number
      // to itimerspec values
      time_spec = strtod(optarg, NULL);
      if (errno != 0) {
        perror("Error during period or deadline parsing");
      }

      seconds = lround(trunc(time_spec));
// fetestexcept skipped. Valid operation as ieee-754 does not enforce its
// implementation.
#if __riscv
#else
      res =
          fetestexcept(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW | FE_UNDERFLOW);
#endif
      if (res != 0) {
        perror("Error during conversion in seconds");
      }
      nanoseconds = lround((time_spec - trunc(time_spec)) * 1000000000);
// fetestexcept skipped. Valid operation as ieee-754 does not enforce its
// implementation.
#if __riscv
#else
      res =
          fetestexcept(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW | FE_UNDERFLOW);
#endif
      if (res != 0) {
        perror("Error during conversion in nanoseconds");
      }
      switch (opt) {
      case 'p':
        period.tv_sec = seconds;
        period.tv_nsec = nanoseconds;
        break;
      case 'd':
        initial_delay.tv_sec = seconds;
        initial_delay.tv_nsec = nanoseconds;
        break;
      }
      break;
    case 't':
      target = strtoul(optarg, NULL, 10);
      if (target < LONG_MIN || target > LONG_MAX) {
        fprintf(stderr, "target PID out of range\n");
        help(argv[0]);
        free(signals_to_send);
        return -1;
      }
      break;
    }
  } while (opt != -1);
  if (num_signals_to_send == 0 || target == 0) {
    fprintf(stderr, "You need both signal and target\n");
    help(argv[0]);
    free(signals_to_send);
    return -1;
  }
  if (num_signals_to_send > 1 && (period.tv_sec <= 0 && period.tv_nsec <= 0)) {
    fprintf(stderr, "You need to have a period to send multiple signals\n");
    help(argv[0]);
    free(signals_to_send);
    return -1;
  }
  res = sigaddset(&mask, SIGRTMAX);
  if (res < 0) {
    fprintf(stderr, "Cannot add SIGRTMAX to mask\n");
    free(signals_to_send);
    return -1;
  }
  res = sigaddset(&mask, SIGINT);
  if (res < 0) {
    fprintf(stderr, "Cannot add SIGINT to mask\n");
    free(signals_to_send);
    return -1;
  }
  res = sigprocmask(SIG_BLOCK, &mask, NULL);
  if (res < 0) {
    fprintf(stderr, "Cannot block SIGRTMAX to mask\n");
    free(signals_to_send);
    return -1;
  }
  memset(&event, 0, sizeof(event));
  // the timer will generate a signal
  event.sigev_notify = SIGEV_SIGNAL;
  // the signal generated by the timer
  event.sigev_signo = SIGRTMAX;
  // creation of the timer
  res = timer_create(CLOCK_REALTIME, &event, &period_timer);
  if (res != 0) {
    perror("Error during HR timer creation");
    free(signals_to_send);
    return res;
  }
  FILE *file = fopen("interupts.log", "w");
  if (file == NULL) {
    perror("Cannot open output file");
    timer_delete(period_timer);
    return -1;
  }
  // setting when the timer must be fired, using the provided deadline
  // parameters
  timer_spec.it_interval = period;
  timer_spec.it_value = initial_delay;
  res = timer_settime(period_timer, 0, &timer_spec, NULL);
  if (res < 0) {
    perror("Error during timer setup");
    timer_delete(period_timer);
    fclose(file);
    free(signals_to_send);
    return res;
  }
  do {
    if (initial_delay.tv_sec > 0 || initial_delay.tv_nsec > 0) {
      res = sigwait(&mask, &recv_sig);
      if (res > 0) {
        perror("cannot wait for timer");
        fclose(file);
        timer_delete(period_timer);
        free(signals_to_send);
        return -1;
      }
    }
    if (recv_sig != SIGINT) {
      fprintf(file, "%lf\n", get_time());
      res = kill(target, signals_to_send[period_id % num_signals_to_send]);
      if (res < 0) {
        perror("Cannot send signal to target process\n");
        return -1;
      }
      printf("sent %d to %d. Next period in %lds and %ldns\n",
             signals_to_send[period_id % num_signals_to_send], target,
             period.tv_sec, period.tv_nsec);
    }
    period_id++;
  } while (recv_sig == SIGRTMAX && (period.tv_sec > 0 || period.tv_nsec > 0));
  timer_delete(period_timer);
  free(signals_to_send);
  fclose(file);
  return 0;
}
