#include "locusta.h"
#include <limits.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>

timer_t period_timer;
static long period_sec = 0, period_nsec = 0;
static int num_signals_to_send = 0,*signals_to_send=NULL, period_id=0;
pid_t target = 0;
static inline double get_time(void) {
  struct timeval tv;
  gettimeofday(&tv, NULL);
  return tv.tv_sec + (double)tv.tv_usec / 1000000;
}

static inline void help(char *name) {
  printf("Usage ./%s -t  target_pid -i signal1[,signal2,...] [-s seconds] [-n nanoseconds]\n",
         name);
}

int main(int argc, char **argv) {
  double boot_time = 0;
  int res, opt, recv_sig=0;
  struct sigaction sa;
  struct sigevent event;
  struct itimerspec timer_spec;
  struct timespec initial_delay;
  sigset_t mask;
  res = sigemptyset(&mask);
  if (res < 0) {
    fprintf(stderr, "Cannot empty signal mask\n");
    return -1;
  }
  do {
    opt = getopt(argc, argv, "-ht:i:s:n:");
    switch (opt) {
    case 'i':
      char* tmp_signal=NULL;
      int signal_to_send=0;
      tmp_signal=strtok(optarg,";,");
      while(tmp_signal!=NULL){
      signal_to_send = strtol(tmp_signal, NULL, 10);
      if (signal_to_send < 0 ||
          signal_to_send > DUMMY_SIGNALS +
                               (SW_DSTS * SW_MODES) + (HW_DSTS + HW_MODES)) {
        fprintf(stderr, "Signal out of range\n");
        help(argv[0]);
        return -1;
      }
      num_signals_to_send++;
      if(signals_to_send==NULL){
	      signals_to_send=malloc(sizeof(int));
	      if(signals_to_send==NULL){
        	fprintf(stderr, "Cannot allocate memory for signal list\n");
		return -1;
	      }

      } else{
		int* new_signals_to_send=reallocarray(signals_to_send,num_signals_to_send,sizeof(int));
	      if(new_signals_to_send==NULL){
        	fprintf(stderr, "Cannot reallocate memory for signal list\n");
		free(signals_to_send);
		return -1;
	      }
	      signals_to_send=new_signals_to_send;
      }
      signals_to_send[num_signals_to_send-1]= MIGRATION_SIGNAL + signal_to_send;
      tmp_signal=strtok(NULL,",");
      }
      break;
    case 's':
      period_sec = strtol(optarg, NULL, 10);
      if (period_sec < LONG_MIN || period_sec > LONG_MAX) {
        fprintf(stderr, "period seconds out of range\n");
        help(argv[0]);
		free(signals_to_send);
        return -1;
      }
      break;
    case 'n':
      period_nsec = strtol(optarg, NULL, 10);
      if (period_nsec < LONG_MIN || period_nsec > LONG_MAX) {
        fprintf(stderr, "period nanoseconds out of range\n");
        help(argv[0]);
		free(signals_to_send);
        return -1;
      }
      break;
    case 't':
      target = strtoul(optarg, NULL, 10);
      if (target < LONG_MIN || target > LONG_MAX) {
        fprintf(stderr, "target PID out of range\n");
        help(argv[0]);
		free(signals_to_send);
        return -1;
      }
      break;
    }
  } while (opt != -1);
  if (num_signals_to_send == 0 ||
      target == 0) {
    fprintf(stderr, "You need both signal and target\n");
    help(argv[0]);
		free(signals_to_send);
    return -1;
  }
  if (num_signals_to_send == 0 && (period_sec <=0 && period_nsec <=0)) {
    fprintf(stderr, "You need to have a period to send multiple signals\n");
    help(argv[0]);
		free(signals_to_send);
    return -1;
  }
  res = sigaddset(&mask, SIGRTMAX);
  if (res < 0) {
    fprintf(stderr, "Cannot add SIGRTMAX to mask\n");
		free(signals_to_send);
    return -1;
  }
  res = sigaddset(&mask, SIGINT);
  if (res < 0) {
    fprintf(stderr, "Cannot add SIGINT to mask\n");
		free(signals_to_send);
    return -1;
  }
  res = sigprocmask(SIG_BLOCK, &mask, NULL);
  if (res < 0) {
    fprintf(stderr, "Cannot block SIGRTMAX to mask\n");
		free(signals_to_send);
    return -1;
  }
  initial_delay.tv_sec = period_sec;
  initial_delay.tv_nsec = period_nsec;
  memset(&event, 0, sizeof(event));
  // the timer will generate a signal
  event.sigev_notify = SIGEV_SIGNAL;
  // the signal generated by the timer
  event.sigev_signo = SIGRTMAX;
  // creation of the timer
  res = timer_create(CLOCK_REALTIME, &event, &period_timer);
  if (res != 0) {
    perror("Error during HR timer creation");
		free(signals_to_send);
    return res;
  }
  FILE *file = fopen("interupts.log", "w");
  if (file == NULL) {
    perror("Cannot open output file");
    timer_delete(period_timer);
    return -1;
  }
  // setting when the timer must be fired, using the provided deadline
  // parameters
  timer_spec.it_interval.tv_sec = period_sec;
  timer_spec.it_interval.tv_nsec = period_nsec;
  timer_spec.it_value = initial_delay;
  res = timer_settime(period_timer, 0, &timer_spec, NULL);
  if (res < 0) {
    perror("Error during timer setup");
    timer_delete(period_timer);
    fclose(file);
		free(signals_to_send);
    return res;
  }
  boot_time = get_time();
  do {
    if (recv_sig == SIGRTMAX || num_signals_to_send >1) {
    res = sigwait(&mask, &recv_sig);
    if (res > 0) {
      perror("cannot wait for timer");
      fclose(file);
      timer_delete(period_timer);
		free(signals_to_send);
      return -1;
    }
    }
    if (recv_sig != SIGINT) {
    fprintf(file, "%lf\n", get_time() - boot_time);
      res = kill(target, signals_to_send[period_id%num_signals_to_send]);
      if (res < 0) {
        perror("Cannot send signal to target process\n");
	return -1;
      }
  printf("sent %d to %d. Next period in %lds and %ldns\n", signals_to_send[period_id%num_signals_to_send], target,
         period_sec, period_nsec);
    }
period_id++;
  } while (recv_sig == SIGRTMAX && num_signals_to_send >1);
  timer_delete(period_timer); free(signals_to_send);
  fclose(file);
  return 0;
}
